/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pds.mvc_customer;

import com.pds.entities.Client;
import com.pds.implobs.AbstractObservable;
import com.pds.implobs.IObserver;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zouhairhajji
 */
public class View_GestClient extends JInternalFrame implements IObserver{

    private DefaultTableModel tableModel;
    private String[] columnsTable;
    private String[] rowsCritere;
    
    private Controller_GestClient controller;
    
    private List<Client> clients;
    private List<Client> clientShown;
    
    private int idSelectedIndex;
    
    public View_GestClient(Controller_GestClient controller) {
        this.clientShown = new LinkedList<>();
        this.controller = controller;
        this.columnsTable = new String[]{"Nom", "Prenom", "Date de naissance", "Sexe", "Code Postale", "Pays de naissance", "Adresse", "Profession", "Situation", "Apport", "Apport du conjoint"};
        this.rowsCritere = new String[]{"Nom",  "Prenom", "Profession", "Données du formulaire"};
        this.tableModel = new DefaultTableModel(columnsTable, 0);
        initComponents();
        controller.askListClient();
        this.jTable1.getSelectionModel().addListSelectionListener(new TableSelecetCellListener());
        this.bVisSimPret.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bVisSimPret = new javax.swing.JButton();
        bVisSimPret1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        iNom = new javax.swing.JTextField();
        iPrenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcDateNaiss = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iCodePostale = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iApportPerso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        iApportConjoint = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAdresse = new javax.swing.JTextArea();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        bVisSimPret2 = new javax.swing.JButton();
        iProfession = new javax.swing.JTextField();
        iSexe = new javax.swing.JTextField();
        iSituation = new javax.swing.JTextField();
        iRevenu = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        iNbrSim = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jTable1.setModel(this.tableModel);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Liste des clients");

        bVisSimPret.setText("Afficher les simulations");
        bVisSimPret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisSimPretActionPerformed(evt);
            }
        });

        bVisSimPret1.setText("rechercher");
        bVisSimPret1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisSimPret1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom : ");

        jLabel3.setText("Prénom :");

        jLabel4.setText("Date Naiss :");

        jLabel5.setText("Sexe :");

        jLabel7.setText("Code Postale :");

        jLabel8.setText("Profession");

        jLabel9.setText("Situation :");

        jLabel10.setText("Apport perso :");

        jLabel11.setText("Apport conjoint;");

        jLabel12.setText("Adresse :");

        taAdresse.setColumns(10
        );
        taAdresse.setLineWrap(true);
        taAdresse.setRows(3
        );
        jScrollPane3.setViewportView(taAdresse);

        jLabel13.setText("Critère :");

        jLabel14.setText("Mot clef :");

        bVisSimPret2.setText("Simuler un prêt ");
        bVisSimPret2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisSimPret2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Revenu : ");

        jLabel15.setText("Nbr Sim :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(bVisSimPret, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVisSimPret2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(bVisSimPret1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(iNom)
                            .addComponent(jcDateNaiss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(iPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iSexe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iSituation, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(iCodePostale, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(iProfession, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iApportPerso)
                            .addComponent(iApportConjoint)
                            .addComponent(iRevenu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(iNbrSim))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(iNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(iCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(iPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(iProfession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jcDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(iApportPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel15)
                                .addComponent(iNbrSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(iSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(iApportConjoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(iSituation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(iRevenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bVisSimPret1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bVisSimPret, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bVisSimPret2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel12)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVisSimPretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisSimPretActionPerformed
        controller.showFrameListSimPret(this.clients.get(this.idSelectedIndex));
    }//GEN-LAST:event_bVisSimPretActionPerformed

    private void bVisSimPret1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisSimPret1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVisSimPret1ActionPerformed

    private void bVisSimPret2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisSimPret2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVisSimPret2ActionPerformed

    @Override
    public boolean update(AbstractObservable sender, String message, Object... data) {
        return false;
    }

    public void chargerTable(List<Client> clients) {
        this.clients = clients;
        this.tableModel.setRowCount(0);
        for(Client client : clients){
            tableModel.addRow(new Object[]{
                client.getFirstName(),
                client.getLastName(),
                client.getDateBirthDate(),
                client.getSexe().getAbv(),
                client.getCodePost(),
                client.getPays().getAlpha2(),
                client.getAdress(),
                client.getInfoPerso().getProfession(),
                client.getInfoPerso().getSituation(),
                client.getInfoPerso().getRevenuMensuel(),
                client.getInfoPerso().getRevenuConjoint()
            });
        }
    }


    
    public class TableSelecetCellListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                if (!((ListSelectionModel) e.getSource()).isSelectionEmpty()) {
                    // Selected
                    bVisSimPret.setEnabled(true);
                    idSelectedIndex = ((ListSelectionModel) e.getSource()).getMinSelectionIndex();
                    System.out.println(clients.get(idSelectedIndex));
                    
                    iNom.setText(clients.get(idSelectedIndex).getFirstName());
                    iPrenom.setText(clients.get(idSelectedIndex).getLastName());
                    jcDateNaiss.setDate(clients.get(idSelectedIndex).getDateBirthDate());
                    iSexe.setText(clients.get(idSelectedIndex).getSexe().getAbv());
                    iCodePostale.setText(clients.get(idSelectedIndex).getCodePost()+"");
                    iProfession.setText(clients.get(idSelectedIndex).getInfoPerso().getProfession());
                    iSituation.setText(clients.get(idSelectedIndex).getInfoPerso().getSituation().getAbv());
                    iApportPerso.setText(clients.get(idSelectedIndex).getInfoPerso().getApportPerso()+"");
                    iApportConjoint.setText(clients.get(idSelectedIndex).getInfoPerso().getAutre()+"");
                    
                    iRevenu.setText(clients.get(idSelectedIndex).getInfoPerso().getRevenuMensuel()+"");
                    taAdresse.setText(clients.get(idSelectedIndex).getAdress());
                    iNbrSim.setText(clients.get(idSelectedIndex).getSimulationsPrets().size()+" simulation(s)");
                } else {
                    // Non-Selected
                    bVisSimPret.setEnabled(false);
                    idSelectedIndex = -1;
                    vider();
                }
            }

        }
        
        public void vider(){
            iNom.setText("");
            iPrenom.setText("");
            jcDateNaiss.setDate(new Date());
            iSexe.setText("");
            iCodePostale.setText("");
            iProfession.setText("");
            iSituation.setText("");
            iApportPerso.setText("");
            iApportConjoint.setText("");
            iRevenu.setText("");
            taAdresse.setText("");
            iNbrSim.setText("");
        }

    }
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bVisSimPret;
    private javax.swing.JButton bVisSimPret1;
    private javax.swing.JButton bVisSimPret2;
    private javax.swing.JTextField iApportConjoint;
    private javax.swing.JTextField iApportPerso;
    private javax.swing.JTextField iCodePostale;
    private javax.swing.JTextField iNbrSim;
    private javax.swing.JTextField iNom;
    private javax.swing.JTextField iPrenom;
    private javax.swing.JTextField iProfession;
    private javax.swing.JTextField iRevenu;
    private javax.swing.JTextField iSexe;
    private javax.swing.JTextField iSituation;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser jcDateNaiss;
    private javax.swing.JTextArea taAdresse;
    // End of variables declaration//GEN-END:variables
}
