/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pds.mvc_indicator;

import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormatSymbols;
import java.util.Vector;

/**
 *
 * @author Poweriser
 */
public class panelIndicatorTable extends javax.swing.JPanel {
    private final Controller_Indicator controller;
    private static List<Integer> loanNumberList;
    private static List<Integer> simNumberList;
    private static List<Integer> loanTimeList;
    private static List<Integer> avgAmountList;
    int selectedmonth;
   //Object [] data,data2,data3,data4;
   

    
  
    public panelIndicatorTable(Controller_Indicator controller) {
        this.controller= controller;
        initComponents();
        selectedmonth = controller.getHistoriquemois();// mois en cours
/*String col[];
        
        col[] = {"Indicateur",new DateFormatSymbols().getMonths()[selectedmonth], new DateFormatSymbols().getMonths()[selectedmonth+1]};
        else if(selectedmonth >= 12)
          String col[] = {"Indicateur", new DateFormatSymbols().getMonths()[selectedmonth-1],new DateFormatSymbols().getMonths()[selectedmonth]};
        else */String col[] = {"Indicateur", new DateFormatSymbols().getMonths()[selectedmonth-1],new DateFormatSymbols().getMonths()[selectedmonth],new DateFormatSymbols().getMonths()[selectedmonth+1]};
       
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
        jTable1.setModel(dtm);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(180);
        
       
        loanNumberList= controller.getIndicator().getLoanNumberResultList();
       simNumberList= controller.getIndicator().getSimNumberResultList();
       loanTimeList= controller.getIndicator().getLoanTimeResultList();
       avgAmountList= controller.getIndicator().getAvgAmountResultList();
    
        System.out.println("mois selectionné " + selectedmonth);
        System.out.println("mois selectionné " + jComboBox1.getSelectedIndex());
        System.out.println("resultat liste = " + loanTimeList.get(3));
        System.out.println("resultat liste[selectedmonth] = " + loanTimeList.get(selectedmonth));
        
        if((selectedmonth -1) <= 0) {
            System.out.println("passage dans cas erreur mois janvier");
        Object[] data = {"Nombre de prêt",  loanNumberList.get(selectedmonth),loanNumberList.get(selectedmonth+1)};
       Object[] data2 = {"Nombre de simulation", simNumberList.get(selectedmonth),simNumberList.get(selectedmonth+1)};
       Object[]     data3 = {"Durée moyenne des prêts", loanTimeList.get(selectedmonth),loanTimeList.get(selectedmonth+1)};
        Object[]     data4 = {"Montant moyen des prêts",avgAmountList.get(selectedmonth),avgAmountList.get(selectedmonth+1)};
       dtm.addRow(data);
            dtm.addRow(data2);
            dtm.addRow(data3);
            dtm.addRow(data4);
        }
        else if ((selectedmonth +1) >= 12) {
       Object[]       data = {"Nombre de prêt",  loanNumberList.get(selectedmonth-1),loanNumberList.get(selectedmonth)};
      Object[]      data2 = {"Nombre de simulation", simNumberList.get(selectedmonth-1),simNumberList.get(selectedmonth)};
      Object[]      data3 = {"Durée moyenne des prêts", loanTimeList.get(selectedmonth-1),loanTimeList.get(selectedmonth)};
      Object[]       data4 = {"Montant moyen des prêts",avgAmountList.get(selectedmonth-1),avgAmountList.get(selectedmonth)};
       dtm.addRow(data);
            dtm.addRow(data2);
            dtm.addRow(data3);
            dtm.addRow(data4);
        }
         else {
      Object[]       data = {"Nombre de prêt",  loanNumberList.get(selectedmonth-1),loanNumberList.get(selectedmonth),loanNumberList.get(selectedmonth+1)};
      Object[]       data2 = {"Nombre de simulation", simNumberList.get(selectedmonth-1),simNumberList.get(selectedmonth),simNumberList.get(selectedmonth+1)};
      Object[]      data3 = {"Durée moyenne des prêts", loanTimeList.get(selectedmonth-1),loanTimeList.get(selectedmonth),loanTimeList.get(selectedmonth +1)} ;
     Object[]        data4 = {"Montant moyen des prêts",avgAmountList.get(selectedmonth-1),avgAmountList.get(selectedmonth),avgAmountList.get(selectedmonth+1)};
       dtm.addRow(data);
            dtm.addRow(data2);
            dtm.addRow(data3);
            dtm.addRow(data4);
        } 
     
        
            
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jCheckBox1.setText("Prêt à la consommation");

        jCheckBox2.setText("Prêt Immobilier");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janvier", "Fevrier", "Mars", "Avril", "Maii", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18 - 25 ans", "26 - 40 ans", "41 -  65 ans", "65 et plus" }));

        jButton1.setText("Rafraichir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        controller.setHistoriquemois(jComboBox1.getSelectedIndex());
        System.out.println("mois selection = " + selectedmonth);
            if(jCheckBox1.isSelected() && jCheckBox2.isSelected() ) {              
           controller.sendLoanNumberRequest("1","1",jComboBox2.getSelectedIndex());
        controller.sendSimNumberRequest("1","1",jComboBox2.getSelectedIndex()); 
            controller.sendAvgAmount("1","1",jComboBox2.getSelectedIndex());
            controller.sendLoanTime("1","1",jComboBox2.getSelectedIndex());
         //   controller.sendInterestEarned("1","1",jComboBox2.getSelectedIndex(),jComboBox1.getSelectedIndex());
            }
            
            else if (jCheckBox1.isSelected()) {
              controller.sendLoanNumberRequest("0","1",jComboBox2.getSelectedIndex());
            controller.sendSimNumberRequest("0","1",jComboBox2.getSelectedIndex());
              controller.sendAvgAmount("0","1",jComboBox2.getSelectedIndex());
            controller.sendLoanTime("0","1",jComboBox2.getSelectedIndex());
          //  controller.sendInterestEarned("0","1",jComboBox2.getSelectedIndex(),jComboBox1.getSelectedIndex());
            }
            else if (jCheckBox2.isSelected()) {
              controller.sendLoanNumberRequest("1","0",jComboBox2.getSelectedIndex());
           controller.sendSimNumberRequest("1","0",jComboBox2.getSelectedIndex());
           controller.sendAvgAmount("1","0",jComboBox2.getSelectedIndex());
            controller.sendLoanTime("1","0",jComboBox2.getSelectedIndex());
          //  controller.sendInterestEarned("1","0",jComboBox2.getSelectedIndex(),jComboBox1.getSelectedIndex());
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
