/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pds.mvc_indicator;

import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poweriser
 */
public class panelIndicatorTable extends javax.swing.JPanel {
    private final Controller_Indicator controller;
    private static List<Integer> loanNumberList;
    private static List<Integer> simNumberList;
    private static List<Integer> loanTimeList;
    private static List<Integer> avgAmountList;

    public panelIndicatorTable(Controller_Indicator controller) {
        this.controller= controller;
        initComponents();
        String col[] = {"Indicateur", "Mois 1", "Mois 2", "Mois 3"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
        jTable1.setModel(dtm);
              
       loanNumberList= controller.getIndicator().getLoanNumberResultList();
       simNumberList= controller.getIndicator().getSimNumberResultList();
       loanTimeList= controller.getIndicator().getLoanTimeResultList();
       avgAmountList= controller.getIndicator().getAvgAmountResultList();
    
       
            Object[] data = {"Nombre de prêt", loanNumberList.get(0), loanNumberList.get(1),loanNumberList.get(2)};
            Object[] data2 = {"Nombre de simulation", simNumberList.get(0), simNumberList.get(1),simNumberList.get(2)};
            Object[] data3 = {"Durée moyenne des prêts", loanTimeList.get(0), loanTimeList.get(1),loanTimeList.get(2)};
            Object[] data4 = {"Montant moyen des prêts", avgAmountList.get(0), avgAmountList.get(1),avgAmountList.get(2)};
            dtm.addRow(data);
            dtm.addRow(data2);
            dtm.addRow(data3);
            dtm.addRow(data4);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jCheckBox1.setText("Prêt à la consommation");

        jCheckBox2.setText("Prêt Immobilier");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janvier", "Fevrier", "Mars", "Avril", "Maii", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18 - 25 ans", "26 - 40 ans", "41 -  65 ans", "65 et plus" }));

        jButton1.setText("Rafraichir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addComponent(jCheckBox2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
            if(jCheckBox1.isSelected() && jCheckBox2.isSelected() ) {              
            controller.sendLoanNumberRequest("1","1",jComboBox1.getSelectedIndex());
            controller.sendSimNumberRequest("1","1",jComboBox1.getSelectedIndex()); 
            controller.sendAvgAmount("1","1",jComboBox1.getSelectedIndex());
            controller.sendLoanTime("1","1",jComboBox1.getSelectedIndex());
            }
            
            else if (jCheckBox1.isSelected()) {
                controller.sendLoanNumberRequest("0","1",jComboBox1.getSelectedIndex());
                controller.sendSimNumberRequest("0","1",jComboBox1.getSelectedIndex());
                controller.sendAvgAmount("0","1",jComboBox1.getSelectedIndex());
            controller.sendLoanTime("0","1",jComboBox1.getSelectedIndex());
            }
            else if (jCheckBox2.isSelected()) {
                controller.sendLoanNumberRequest("1","0",jComboBox1.getSelectedIndex());
            controller.sendSimNumberRequest("1","0",jComboBox1.getSelectedIndex());
            controller.sendAvgAmount("1","0",jComboBox1.getSelectedIndex());
            controller.sendLoanTime("1","0",jComboBox1.getSelectedIndex());
            
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
