/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pds.mvc_indicator;



import com.pds.implobs.AbstractObservable;
import com.pds.implobs.IObserver;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Poweriser
 */
public class View_Indicator extends javax.swing.JInternalFrame implements IObserver {

    /**
     * Creates new form View_Indicator
     */
    MainGraphics2 m;
private Controller_Indicator controller;
    
    public View_Indicator(Controller_Indicator controller) {
           this.controller = controller;
           initComponents();
            m=new MainGraphics2 (controller);
        this.getContentPane().add(m);
        this.setSize(1350,670);
        

       // this.jToggleButton1.addActionListener(new IndicatorListener());
              
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean update(AbstractObservable sender, String message, Object... data) {

      
        switch(message.trim()){ 
       case "sendLoanNumbers" :
           //    jTextField1.setText("il y a eu du changement");
           System.out.println("le resultat est 12h31 :" + data.toString());
          this.remove(m);
          this.repaint();
          
          m=new MainGraphics2(controller);
          this.add(m);
          this.validate();
                return true;
         case "sendAvgAge" :
           //    jTextField1.setText("il y a eu du changement");
                   System.out.println("resultat indicator niveau view" +controller.getIndicator().getResultats().get(0));

           System.out.println("le resultat est 12h30:" + data);
          this.remove(m);
          this.repaint();
          m=new MainGraphics2(controller);
          this.add(m);
          this.validate();
                return true;
      default :
                return false;         
        }
        
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
