/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package com.pds.graphics;

import com.pds.entities.CalculPret;
import com.pds.entities.SimulationPret;
import com.pds.entities.Taux_directeur;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nodaro
 */
public class AmortisationTablePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form AmortisationTablePanel
     */
    
    public AmortisationTablePanel(SimulationPret loanSimulation)  {
        
        initComponents();
        List<Double> capPayed=new ArrayList<Double>();
        capPayed=loanSimulation.calcCapAmmort();   //capital payed
        List<Double> capToRefund=new ArrayList<Double>();
        capToRefund=loanSimulation.calcCapRestant(); //captital to refund
        List<Double> calcInterests=new ArrayList<Double>();
        calcInterests=loanSimulation.calcInterets(); //interests
        double insurance=loanSimulation.calcAssurance();    //insurance
        double totalToPay=loanSimulation.calcMensualite(); //total to pay
        
        String col[] = {"Mois", "Montant remboursé", "Intérêts", "Montant restant à rembourser", "Assurance", "Coût total"};
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
        jTable1.setModel(dtm);
        for (int i=0;i<loanSimulation.getDureePret();i++){      //print values in the cells
            Object[] data = {i+1, capPayed.get(i), calcInterests.get(i),capToRefund.get(i),insurance,totalToPay
            };
            dtm.addRow(data);
        }
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);        //columns jTable width
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i=0;i<jTable1.getColumnCount();i++)
            jTable1.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);   //center values in jtable
        ((DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);         //centrer titles in header
        this.setVisible(true);
        //this.setSize(650, 500);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mois", "Date", "Montant remboursé", "Intérêts", "Montant restant à rembourser", "Assurance", "Coût total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Tableau d'amortissement mensuel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void main (String args[]){
        SimulationPret sim = new SimulationPret();
        sim.setDureePret(12);
        sim.setMtPret(10000);
        CalculPret calculPret = new CalculPret();
        calculPret.setCoef_assurance(2);
        calculPret.setT_marge(2);
        Taux_directeur tauxDir = new Taux_directeur(0);
        calculPret.setTauxDirecteur(tauxDir);
        sim.setCalcPret(calculPret);
        AmortisationTablePanel am=new AmortisationTablePanel(sim);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
